export default [
  {
    countryCode: 'AD',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'AE',
    currencyCode: 'AED',
    symbol: 'AED',
    name: 'United Arab Emirates Dirham',
    name_plural: 'UAE dirhams',
  },
  {
    countryCode: 'AF',
    currencyCode: 'AFN',
    symbol: 'Af',
    name: 'Afghan Afghani',
    name_plural: 'Afghan Afghanis',
  },
  {
    countryCode: 'AL',
    currencyCode: 'ALL',
    symbol: 'ALL',
    name: 'Albanian Lek',
    name_plural: 'Albanian lekë',
  },
  {
    countryCode: 'AM',
    currencyCode: 'AMD',
    symbol: 'AMD',
    name: 'Armenian Dram',
    name_plural: 'Armenian drams',
  },
  {
    countryCode: 'AR',
    currencyCode: 'ARS',
    symbol: 'AR$',
    name: 'Argentine Peso',
    name_plural: 'Argentine pesos',
  },
  {
    countryCode: 'AS',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'AT',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'AU',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'AX',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'AZ',
    currencyCode: 'AZN',
    symbol: 'man.',
    name: 'Azerbaijani Manat',
    name_plural: 'Azerbaijani manats',
  },
  {
    countryCode: 'BA',
    currencyCode: 'BAM',
    symbol: 'KM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    name_plural: 'Bosnia-Herzegovina convertible marks',
  },
  {
    countryCode: 'BD',
    currencyCode: 'BDT',
    symbol: 'Tk',
    name: 'Bangladeshi Taka',
    name_plural: 'Bangladeshi takas',
  },
  {
    countryCode: 'BE',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'BF',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'BG',
    currencyCode: 'BGN',
    symbol: 'BGN',
    name: 'Bulgarian Lev',
    name_plural: 'Bulgarian leva',
  },
  {
    countryCode: 'BH',
    currencyCode: 'BHD',
    symbol: 'BD',
    name: 'Bahraini Dinar',
    name_plural: 'Bahraini dinars',
  },
  {
    countryCode: 'BI',
    currencyCode: 'BIF',
    symbol: 'FBu',
    name: 'Burundian Franc',
    name_plural: 'Burundian francs',
  },
  {
    countryCode: 'BJ',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'BL',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'BN',
    currencyCode: 'BND',
    symbol: 'BN$',
    name: 'Brunei Dollar',
    name_plural: 'Brunei dollars',
  },
  {
    countryCode: 'BO',
    currencyCode: 'BOB',
    symbol: 'Bs',
    name: 'Bolivian Boliviano',
    name_plural: 'Bolivian bolivianos',
  },
  {
    countryCode: 'BQ',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'BR',
    currencyCode: 'BRL',
    symbol: 'R$',
    name: 'Brazilian Real',
    name_plural: 'Brazilian reals',
  },
  {
    countryCode: 'BV',
    currencyCode: 'NOK',
    symbol: 'Nkr',
    name: 'Norwegian Krone',
    name_plural: 'Norwegian kroner',
  },
  {
    countryCode: 'BW',
    currencyCode: 'BWP',
    symbol: 'BWP',
    name: 'Botswanan Pula',
    name_plural: 'Botswanan pulas',
  },
  {
    countryCode: 'BZ',
    currencyCode: 'BZD',
    symbol: 'BZ$',
    name: 'Belize Dollar',
    name_plural: 'Belize dollars',
  },
  {
    countryCode: 'CA',
    currencyCode: 'CAD',
    symbol: 'CA$',
    name: 'Canadian Dollar',
    name_plural: 'Canadian dollars',
  },
  {
    countryCode: 'CC',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'CD',
    currencyCode: 'CDF',
    symbol: 'CDF',
    name: 'Congolese Franc',
    name_plural: 'Congolese francs',
  },
  {
    countryCode: 'CF',
    currencyCode: 'XAF',
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
  },
  {
    countryCode: 'CG',
    currencyCode: 'XAF',
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
  },
  {
    countryCode: 'CH',
    currencyCode: 'CHF',
    symbol: 'CHF',
    name: 'Swiss Franc',
    name_plural: 'Swiss francs',
  },
  {
    countryCode: 'CI',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'CK',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand dollars',
  },
  {
    countryCode: 'CL',
    currencyCode: 'CLP',
    symbol: 'CL$',
    name: 'Chilean Peso',
    name_plural: 'Chilean pesos',
  },
  {
    countryCode: 'CM',
    currencyCode: 'XAF',
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
  },
  {
    countryCode: 'CN',
    currencyCode: 'CNY',
    symbol: 'CN¥',
    name: 'Chinese Yuan',
    name_plural: 'Chinese yuan',
  },
  {
    countryCode: 'CO',
    currencyCode: 'COP',
    symbol: 'CO$',
    name: 'Colombian Peso',
    name_plural: 'Colombian pesos',
  },
  {
    countryCode: 'CR',
    currencyCode: 'CRC',
    symbol: '₡',
    name: 'Costa Rican Colón',
    name_plural: 'Costa Rican colóns',
  },
  {
    countryCode: 'CV',
    currencyCode: 'CVE',
    symbol: 'CV$',
    name: 'Cape Verdean Escudo',
    name_plural: 'Cape Verdean escudos',
  },
  {
    countryCode: 'CX',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'CY',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'CZ',
    currencyCode: 'CZK',
    symbol: 'Kč',
    name: 'Czech Republic Koruna',
    name_plural: 'Czech Republic korunas',
  },
  {
    countryCode: 'DE',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'DJ',
    currencyCode: 'DJF',
    symbol: 'Fdj',
    name: 'Djiboutian Franc',
    name_plural: 'Djiboutian francs',
  },
  {
    countryCode: 'DK',
    currencyCode: 'DKK',
    symbol: 'Dkr',
    name: 'Danish Krone',
    name_plural: 'Danish kroner',
  },
  {
    countryCode: 'DO',
    currencyCode: 'DOP',
    symbol: 'RD$',
    name: 'Dominican Peso',
    name_plural: 'Dominican pesos',
  },
  {
    countryCode: 'DZ',
    currencyCode: 'DZD',
    symbol: 'DA',
    name: 'Algerian Dinar',
    name_plural: 'Algerian dinars',
  },
  {
    countryCode: 'EC',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'EE',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'EG',
    currencyCode: 'EGP',
    symbol: 'EGP',
    name: 'Egyptian Pound',
    name_plural: 'Egyptian pounds',
  },
  {
    countryCode: 'EH',
    currencyCode: 'MAD',
    symbol: 'MAD',
    name: 'Moroccan Dirham',
    name_plural: 'Moroccan dirhams',
  },
  {
    countryCode: 'ER',
    currencyCode: 'ERN',
    symbol: 'Nfk',
    name: 'Eritrean Nakfa',
    name_plural: 'Eritrean nakfas',
  },
  {
    countryCode: 'ES',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'ET',
    currencyCode: 'ETB',
    symbol: 'Br',
    name: 'Ethiopian Birr',
    name_plural: 'Ethiopian birrs',
  },
  {
    countryCode: 'FI',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'FM',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'FO',
    currencyCode: 'DKK',
    symbol: 'Dkr',
    name: 'Danish Krone',
    name_plural: 'Danish kroner',
  },
  {
    countryCode: 'FR',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'GA',
    currencyCode: 'XAF',
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
  },
  {
    countryCode: 'GB',
    currencyCode: 'GBP',
    symbol: '£',
    name: 'British Pound Sterling',
    name_plural: 'British pounds sterling',
  },
  {
    countryCode: 'GE',
    currencyCode: 'GEL',
    symbol: 'GEL',
    name: 'Georgian Lari',
    name_plural: 'Georgian laris',
  },
  {
    countryCode: 'GF',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'GG',
    currencyCode: 'GBP',
    symbol: '£',
    name: 'British Pound Sterling',
    name_plural: 'British pounds sterling',
  },
  {
    countryCode: 'GH',
    currencyCode: 'GHS',
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
    name_plural: 'Ghanaian cedis',
  },
  {
    countryCode: 'GL',
    currencyCode: 'DKK',
    symbol: 'Dkr',
    name: 'Danish Krone',
    name_plural: 'Danish kroner',
  },
  {
    countryCode: 'GN',
    currencyCode: 'GNF',
    symbol: 'FG',
    name: 'Guinean Franc',
    name_plural: 'Guinean francs',
  },
  {
    countryCode: 'GP',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'GQ',
    currencyCode: 'XAF',
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
  },
  {
    countryCode: 'GR',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'GS',
    currencyCode: 'GBP',
    symbol: '£',
    name: 'British Pound Sterling',
    name_plural: 'British pounds sterling',
  },
  {
    countryCode: 'GT',
    currencyCode: 'GTQ',
    symbol: 'GTQ',
    name: 'Guatemalan Quetzal',
    name_plural: 'Guatemalan quetzals',
  },
  {
    countryCode: 'GU',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'GW',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'HK',
    currencyCode: 'HKD',
    symbol: 'HK$',
    name: 'Hong Kong Dollar',
    name_plural: 'Hong Kong dollars',
  },
  {
    countryCode: 'HM',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'HN',
    currencyCode: 'HNL',
    symbol: 'HNL',
    name: 'Honduran Lempira',
    name_plural: 'Honduran lempiras',
  },
  {
    countryCode: 'HR',
    currencyCode: 'HRK',
    symbol: 'kn',
    name: 'Croatian Kuna',
    name_plural: 'Croatian kunas',
  },
  {
    countryCode: 'HU',
    currencyCode: 'HUF',
    symbol: 'Ft',
    name: 'Hungarian Forint',
    name_plural: 'Hungarian forints',
  },
  {
    countryCode: 'ID',
    currencyCode: 'IDR',
    symbol: 'Rp',
    name: 'Indonesian Rupiah',
    name_plural: 'Indonesian rupiahs',
  },
  {
    countryCode: 'IE',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'IL',
    currencyCode: 'ILS',
    symbol: '₪',
    name: 'Israeli New Sheqel',
    name_plural: 'Israeli new sheqels',
  },
  {
    countryCode: 'IM',
    currencyCode: 'GBP',
    symbol: '£',
    name: 'British Pound Sterling',
    name_plural: 'British pounds sterling',
  },
  {
    countryCode: 'IN',
    currencyCode: 'INR',
    symbol: 'Rs',
    name: 'Indian Rupee',
    name_plural: 'Indian rupees',
  },
  {
    countryCode: 'IO',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'IQ',
    currencyCode: 'IQD',
    symbol: 'IQD',
    name: 'Iraqi Dinar',
    name_plural: 'Iraqi dinars',
  },
  {
    countryCode: 'IR',
    currencyCode: 'IRR',
    symbol: 'IRR',
    name: 'Iranian Rial',
    name_plural: 'Iranian rials',
  },
  {
    countryCode: 'IS',
    currencyCode: 'ISK',
    symbol: 'Ikr',
    name: 'Icelandic Króna',
    name_plural: 'Icelandic krónur',
  },
  {
    countryCode: 'IT',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'JE',
    currencyCode: 'GBP',
    symbol: '£',
    name: 'British Pound Sterling',
    name_plural: 'British pounds sterling',
  },
  {
    countryCode: 'JM',
    currencyCode: 'JMD',
    symbol: 'J$',
    name: 'Jamaican Dollar',
    name_plural: 'Jamaican dollars',
  },
  {
    countryCode: 'JO',
    currencyCode: 'JOD',
    symbol: 'JD',
    name: 'Jordanian Dinar',
    name_plural: 'Jordanian dinars',
  },
  {
    countryCode: 'JP',
    currencyCode: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen',
    name_plural: 'Japanese yen',
  },
  {
    countryCode: 'KE',
    currencyCode: 'KES',
    symbol: 'Ksh',
    name: 'Kenyan Shilling',
    name_plural: 'Kenyan shillings',
  },
  {
    countryCode: 'KH',
    currencyCode: 'KHR',
    symbol: 'KHR',
    name: 'Cambodian Riel',
    name_plural: 'Cambodian riels',
  },
  {
    countryCode: 'KI',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'KM',
    currencyCode: 'KMF',
    symbol: 'CF',
    name: 'Comorian Franc',
    name_plural: 'Comorian francs',
  },
  {
    countryCode: 'KR',
    currencyCode: 'KRW',
    symbol: '₩',
    name: 'South Korean Won',
    name_plural: 'South Korean won',
  },
  {
    countryCode: 'KW',
    currencyCode: 'KWD',
    symbol: 'KD',
    name: 'Kuwaiti Dinar',
    name_plural: 'Kuwaiti dinars',
  },
  {
    countryCode: 'KZ',
    currencyCode: 'KZT',
    symbol: 'KZT',
    name: 'Kazakhstani Tenge',
    name_plural: 'Kazakhstani tenges',
  },
  {
    countryCode: 'LB',
    currencyCode: 'LBP',
    symbol: 'LB£',
    name: 'Lebanese Pound',
    name_plural: 'Lebanese pounds',
  },
  {
    countryCode: 'LI',
    currencyCode: 'CHF',
    symbol: 'CHF',
    name: 'Swiss Franc',
    name_plural: 'Swiss francs',
  },
  {
    countryCode: 'LK',
    currencyCode: 'LKR',
    symbol: 'SLRs',
    name: 'Sri Lankan Rupee',
    name_plural: 'Sri Lankan rupees',
  },
  {
    countryCode: 'LT',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'LU',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'LV',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'LY',
    currencyCode: 'LYD',
    symbol: 'LD',
    name: 'Libyan Dinar',
    name_plural: 'Libyan dinars',
  },
  {
    countryCode: 'MA',
    currencyCode: 'MAD',
    symbol: 'MAD',
    name: 'Moroccan Dirham',
    name_plural: 'Moroccan dirhams',
  },
  {
    countryCode: 'MC',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'MD',
    currencyCode: 'MDL',
    symbol: 'MDL',
    name: 'Moldovan Leu',
    name_plural: 'Moldovan lei',
  },
  {
    countryCode: 'ME',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'MF',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'MG',
    currencyCode: 'MGA',
    symbol: 'MGA',
    name: 'Malagasy Ariary',
    name_plural: 'Malagasy Ariaries',
  },
  {
    countryCode: 'MH',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'MK',
    currencyCode: 'MKD',
    symbol: 'MKD',
    name: 'Macedonian Denar',
    name_plural: 'Macedonian denari',
  },
  {
    countryCode: 'ML',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'MM',
    currencyCode: 'MMK',
    symbol: 'MMK',
    name: 'Myanma Kyat',
    name_plural: 'Myanma kyats',
  },
  {
    countryCode: 'MO',
    currencyCode: 'MOP',
    symbol: 'MOP$',
    name: 'Macanese Pataca',
    name_plural: 'Macanese patacas',
  },
  {
    countryCode: 'MP',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'MQ',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'MT',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'MU',
    currencyCode: 'MUR',
    symbol: 'MURs',
    name: 'Mauritian Rupee',
    name_plural: 'Mauritian rupees',
  },
  {
    countryCode: 'MX',
    currencyCode: 'MXN',
    symbol: 'MX$',
    name: 'Mexican Peso',
    name_plural: 'Mexican pesos',
  },
  {
    countryCode: 'MY',
    currencyCode: 'MYR',
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    name_plural: 'Malaysian ringgits',
  },
  {
    countryCode: 'MZ',
    currencyCode: 'MZN',
    symbol: 'MTn',
    name: 'Mozambican Metical',
    name_plural: 'Mozambican meticals',
  },
  {
    countryCode: 'NA',
    currencyCode: 'NAD',
    symbol: 'N$',
    name: 'Namibian Dollar',
    name_plural: 'Namibian dollars',
  },
  {
    countryCode: 'NE',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'NF',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'NG',
    currencyCode: 'NGN',
    symbol: '₦',
    name: 'Nigerian Naira',
    name_plural: 'Nigerian nairas',
  },
  {
    countryCode: 'NI',
    currencyCode: 'NIO',
    symbol: 'C$',
    name: 'Nicaraguan Córdoba',
    name_plural: 'Nicaraguan córdobas',
  },
  {
    countryCode: 'NL',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'NO',
    currencyCode: 'NOK',
    symbol: 'Nkr',
    name: 'Norwegian Krone',
    name_plural: 'Norwegian kroner',
  },
  {
    countryCode: 'NP',
    currencyCode: 'NPR',
    symbol: 'NPRs',
    name: 'Nepalese Rupee',
    name_plural: 'Nepalese rupees',
  },
  {
    countryCode: 'NR',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'NU',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand dollars',
  },
  {
    countryCode: 'NZ',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand dollars',
  },
  {
    countryCode: 'OM',
    currencyCode: 'OMR',
    symbol: 'OMR',
    name: 'Omani Rial',
    name_plural: 'Omani rials',
  },
  {
    countryCode: 'PA',
    currencyCode: 'PAB',
    symbol: 'B/.',
    name: 'Panamanian Balboa',
    name_plural: 'Panamanian balboas',
  },
  {
    countryCode: 'PE',
    currencyCode: 'PEN',
    symbol: 'S/.',
    name: 'Peruvian Nuevo Sol',
    name_plural: 'Peruvian nuevos soles',
  },
  {
    countryCode: 'PH',
    currencyCode: 'PHP',
    symbol: '₱',
    name: 'Philippine Peso',
    name_plural: 'Philippine pesos',
  },
  {
    countryCode: 'PK',
    currencyCode: 'PKR',
    symbol: 'PKRs',
    name: 'Pakistani Rupee',
    name_plural: 'Pakistani rupees',
  },
  {
    countryCode: 'PL',
    currencyCode: 'PLN',
    symbol: 'zł',
    name: 'Polish Zloty',
    name_plural: 'Polish zlotys',
  },
  {
    countryCode: 'PM',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'PN',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand dollars',
  },
  {
    countryCode: 'PR',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'PS',
    currencyCode: 'ILS',
    symbol: '₪',
    name: 'Israeli New Sheqel',
    name_plural: 'Israeli new sheqels',
  },
  {
    countryCode: 'PT',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'PW',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'PY',
    currencyCode: 'PYG',
    symbol: '₲',
    name: 'Paraguayan Guarani',
    name_plural: 'Paraguayan guaranis',
  },
  {
    countryCode: 'QA',
    currencyCode: 'QAR',
    symbol: 'QR',
    name: 'Qatari Rial',
    name_plural: 'Qatari rials',
  },
  {
    countryCode: 'RE',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'RO',
    currencyCode: 'RON',
    symbol: 'RON',
    name: 'Romanian Leu',
    name_plural: 'Romanian lei',
  },
  {
    countryCode: 'RS',
    currencyCode: 'RSD',
    symbol: 'din.',
    name: 'Serbian Dinar',
    name_plural: 'Serbian dinars',
  },
  {
    countryCode: 'RU',
    currencyCode: 'RUB',
    symbol: 'RUB',
    name: 'Russian Ruble',
    name_plural: 'Russian rubles',
  },
  {
    countryCode: 'RW',
    currencyCode: 'RWF',
    symbol: 'RWF',
    name: 'Rwandan Franc',
    name_plural: 'Rwandan francs',
  },
  {
    countryCode: 'SA',
    currencyCode: 'SAR',
    symbol: 'SR',
    name: 'Saudi Riyal',
    name_plural: 'Saudi riyals',
  },
  {
    countryCode: 'SD',
    currencyCode: 'SDG',
    symbol: 'SDG',
    name: 'Sudanese Pound',
    name_plural: 'Sudanese pounds',
  },
  {
    countryCode: 'SE',
    currencyCode: 'SEK',
    symbol: 'Skr',
    name: 'Swedish Krona',
    name_plural: 'Swedish kronor',
  },
  {
    countryCode: 'SG',
    currencyCode: 'SGD',
    symbol: 'S$',
    name: 'Singapore Dollar',
    name_plural: 'Singapore dollars',
  },
  {
    countryCode: 'SI',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'SJ',
    currencyCode: 'NOK',
    symbol: 'Nkr',
    name: 'Norwegian Krone',
    name_plural: 'Norwegian kroner',
  },
  {
    countryCode: 'SK',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'SM',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'SN',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'SO',
    currencyCode: 'SOS',
    symbol: 'Ssh',
    name: 'Somali Shilling',
    name_plural: 'Somali shillings',
  },
  {
    countryCode: 'SV',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'SY',
    currencyCode: 'SYP',
    symbol: 'SY£',
    name: 'Syrian Pound',
    name_plural: 'Syrian pounds',
  },
  {
    countryCode: 'TC',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'TD',
    currencyCode: 'XAF',
    symbol: 'FCFA',
    name: 'CFA Franc BEAC',
    name_plural: 'CFA francs BEAC',
  },
  {
    countryCode: 'TF',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'TG',
    currencyCode: 'XOF',
    symbol: 'CFA',
    name: 'CFA Franc BCEAO',
    name_plural: 'CFA francs BCEAO',
  },
  {
    countryCode: 'TH',
    currencyCode: 'THB',
    symbol: '฿',
    name: 'Thai Baht',
    name_plural: 'Thai baht',
  },
  {
    countryCode: 'TK',
    currencyCode: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand dollars',
  },
  {
    countryCode: 'TL',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'TN',
    currencyCode: 'TND',
    symbol: 'DT',
    name: 'Tunisian Dinar',
    name_plural: 'Tunisian dinars',
  },
  {
    countryCode: 'TO',
    currencyCode: 'TOP',
    symbol: 'T$',
    name: 'Tongan Paʻanga',
    name_plural: 'Tongan paʻanga',
  },
  {
    countryCode: 'TR',
    currencyCode: 'TRY',
    symbol: 'TL',
    name: 'Turkish Lira',
    name_plural: 'Turkish Lira',
  },
  {
    countryCode: 'TT',
    currencyCode: 'TTD',
    symbol: 'TT$',
    name: 'Trinidad and Tobago Dollar',
    name_plural: 'Trinidad and Tobago dollars',
  },
  {
    countryCode: 'TV',
    currencyCode: 'AUD',
    symbol: 'AU$',
    name: 'Australian Dollar',
    name_plural: 'Australian dollars',
  },
  {
    countryCode: 'TW',
    currencyCode: 'TWD',
    symbol: 'NT$',
    name: 'New Taiwan Dollar',
    name_plural: 'New Taiwan dollars',
  },
  {
    countryCode: 'TZ',
    currencyCode: 'TZS',
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    name_plural: 'Tanzanian shillings',
  },
  {
    countryCode: 'UA',
    currencyCode: 'UAH',
    symbol: '₴',
    name: 'Ukrainian Hryvnia',
    name_plural: 'Ukrainian hryvnias',
  },
  {
    countryCode: 'UG',
    currencyCode: 'UGX',
    symbol: 'USh',
    name: 'Ugandan Shilling',
    name_plural: 'Ugandan shillings',
  },
  {
    countryCode: 'UM',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'US',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'UY',
    currencyCode: 'UYU',
    symbol: '$U',
    name: 'Uruguayan Peso',
    name_plural: 'Uruguayan pesos',
  },
  {
    countryCode: 'UZ',
    currencyCode: 'UZS',
    symbol: 'UZS',
    name: 'Uzbekistan Som',
    name_plural: 'Uzbekistan som',
  },
  {
    countryCode: 'VA',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'VE',
    currencyCode: 'VEF',
    symbol: 'Bs.F.',
    name: 'Venezuelan Bolívar',
    name_plural: 'Venezuelan bolívars',
  },
  {
    countryCode: 'VG',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'VI',
    currencyCode: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US dollars',
  },
  {
    countryCode: 'VN',
    currencyCode: 'VND',
    symbol: '₫',
    name: 'Vietnamese Dong',
    name_plural: 'Vietnamese dong',
  },
  {
    countryCode: 'XK',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'YE',
    currencyCode: 'YER',
    symbol: 'YR',
    name: 'Yemeni Rial',
    name_plural: 'Yemeni rials',
  },
  {
    countryCode: 'YT',
    currencyCode: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'euros',
  },
  {
    countryCode: 'ZA',
    currencyCode: 'ZAR',
    symbol: 'R',
    name: 'South African Rand',
    name_plural: 'South African rand',
  },
  {
    countryCode: 'ZW',
    currencyCode: 'ZWL',
    symbol: 'ZWL$',
    name: 'Zimbabwean Dollar',
    name_plural: 'Zimbabwean Dollar',
  },
] as Array<{
  countryCode: string;
  currencyCode: string;
  symbol: string;
  name: string;
  name_plural: string;
}>;
